default: &default
  adapter: postgresql
  encoding: unicode
development:
  <<: *default
  database: mobile_rails_api_dev
  username: root
  password: root
 

production:
  <<: *default
  database: mobile_rails_api_production
  username: root
  password: root